/**
 * The boot mark: a banana silhouette, traced from artwork.
 *
 * Three rounds of drawing this procedurally were thrown away first. A
 * solid crescent read as a moon; three tapered lobes meeting at a
 * junction read as a propeller, because three lobes radiating from a
 * point IS a propeller whatever the parameters. The shape wanted is a
 * specific drawing, and the way to get a specific drawing is to trace it.
 *
 * Stored at RASTER resolution (212 x 208), not logical.
 *
 * That is the whole reason the edges are smooth. The panel is 176x132
 * logical at scale 2, so a mark stored at logical size has every one of
 * its pixels blown up into a 2x2 block, and every curve stair-steps in
 * chunks twice as coarse as the screen can actually show. Storing it at
 * device resolution and blitting 1:1 halves the step, at the cost of 4x
 * the data — 7KB of base64, which is nothing.
 *
 * Traced at a 50% coverage cutoff, which suits a filled shape; the
 * earlier line-art version needed 15% or its thin strokes vanished.
 */

/** Dimensions in RASTER pixels — divide by the LCD scale for logical. */
export const MARK_W = 212;
export const MARK_H = 208;

const PACKED =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//8AAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAB///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///wAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAP//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//+AAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAA///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'B//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//AAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/+AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAH/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAf/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//AAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAA//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB' +
  '//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/+AAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//wAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAP/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAB//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAH//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/' +
  '/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//+AAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//8AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAD///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///8AAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAP///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///+AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAH////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'Af////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////' +
  '/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////gAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAP/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAB//////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////AAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAH//////wAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////8AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAA///////gAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////4AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAD///////AAAAAAAAAAAAAAAAAAAAAAAAAAAB///////wAAAAAAAAAAAAAAAAAAAAAAAAAAAf/' +
  '/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAH///////AAAAAAAAAAAAAAAAAAAAAAAAAAAD///////' +
  '4AAAAAAAAAAAAAAAAAAAAAAAAAAA///////+AAAAAAAAAAAAAAAAAAAAAAAAAAAP///////gAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAH///////4AAAAAAAAAAAAAAAAAAAAAAAAAAB///////+AAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAf///////gAAAAAAAAAAAAAAAAAAAAAAAAAAH///////8AAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAD////////AAAAAAAAAAAAAAAAAAAAAAAAAAA////////wAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAP///////8AAAAAAAAAAAAAAAAAAAAAAAAAAD////////AAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'B////////wAAAAAAAAAAAAAAAAAAAAAAAAAAf///////8AAAAAAAAAAAAAAAAAAAAAAAAAAH////' +
  '////AAAAAAAAAAAAAAAAAAAAAAAAAAB////////wAAAAAAAAAAAAAAAAAAAAAAAAAA////////8A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAP////////AAAAAAAAAAAAAAAAAAAAAAAAAAH////////wAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAB////////8AAAAAAAAAAAAAAAAAAAAAAAAAAf////////AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAP////////wAAAAAAAAAAAAAAAAAAAAAAAAAD////////8AAAAAAAAAAAAAAAAA' +
  'AAAAAAAAA////////+AAAAAAAAAAAAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAH////////4AAAAAAAAAAAAAAAAAAAAAAAAAB////////+AAAAAAAAAAAAAAAAAAAAAAAAAA//' +
  '///////gAAAAAAAAAAAAAAAAAAAAAAAAAP////////4AAAAAAAAAAAAAAAAAAAAAAAAAD///////' +
  '/+AAAAAAAAAAAAAAAAAAAAAAAAAB/////////AAAAAAAAAAAAAAAAAAAAAAAAAAf////////wAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAP////////8AAAAAAAAAAAAAAAAAAAAAAAAAD/////////AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAB/////////wAAAAAAAAAAAAAAAAAAAAAAAAAf////////4AAAAAAAAAAAAAA' +
  'AAAAAAAAAAAP////////+AAAAAAAAAAAAAAAAAAAAAAAAAH/////////gAAAAAAAAAAAAAAAAAAA' +
  'AAAAAB/////////4AAAAAAAAAAAAAAAAAAAAAAAAA/////////8AAAAAAAAAAAAAAAAAAAAAAAAA' +
  'P/////////AAAAAAAAAAAAAAAAAAAAAAAAAH/////////wAAAAAAAAAAAAAAAAAAAAAAAAD/////' +
  '////8AAAAAAAAAAAAAAAAAAAAAAAAB/////////+AAAAAAAAAAAAAAAAAAAAAAAAAf/////////g' +
  'AAAAAAAAAAAAAAAAAAAAAAAAP/////////4AAAAAAAAAAAAAAAAAAAAAAAAD/////////8AAAAAA' +
  'AAAAAAAAAAAAAAAAAAB//////////AAAAAAAAAAAAAAAAAAAAAAAAA//////////gAAAAAAAAAAA' +
  'AAAAAAAAAAAAAf/////////4AAAAAAAAAAAAAAAAAAAAAAAAP/////////8AAAAAAAAAAAAAAAAA' +
  'AAAAAAAD//////////AAAAAAAAAAAAAAAAAAAAAAAAB//////////wAAAAAAAAAAAAAAAAAAAAAA' +
  'AA//////////4AAAAAAAAAAAAAAAAAAAAAAAAf/////////+AAAAAAAAAAAAAAAAAAAAAAAAH///' +
  '///////gAAAAAAAAAAAAAAAAAAAAAAAH//////////wAAAAAAAAAAAAAAAAAAAAAAAD/////////' +
  '/8AAAAAAAAAAAAAAAAAAAAAAAB//////////+AAAAAAAAAAAAAAAAAAAAAAAA///////////gAAA' +
  'AAAAAAAAAAAAAAAAAAAAf//////////wAAAAAAAAAAAAAAAAAAAAAAAP//////////8AAAAAAAAA' +
  'AAAAAAAAAAAAAAH//////////+AAAAAAAAAAAAAAAAAAAAAAAD///////////gAAAAAAAAAAAAAA' +
  'AAAAAAAAD///////////wAAAAAAAAAAAAAAAAAAAAAAB///////////8AAAAAAAAAAAAAAAAAAAA' +
  'AAA///////////+AAAAAAAAAAAAAAAAAAAAAAAf///////////gAAAAAAAAAAAAAAAAAAAAAAf//' +
  '/////////wAAAAAAAAAAAAAAAAAAAAAAP///////////4AAAAAAAAAAAAAAAAAAAAAAP////////' +
  '///+AAAAAAAAAAAAAAAAAAAAAAH////////////AAAAAAAAAAAAAAAAAAAAAAD////////////wA' +
  'AAAAAAAAAAAAAAAAAAAAD////////////4AAAAAAAAAAAAAAAAAAAAAD////////////8AAAAAAA' +
  'AAAAAAAAAAAAAAD/////////////AAAAAAAAAAAAAAAAAAAAAD/////////////gAAAAAAAAAAAA' +
  'AAAAAAAAB/////////////wAAAAAAAAAAAAAAAAAAAAD/////////////8AAAAAAAAAAAAAAAAAA' +
  'AAD/////////////+AAAAAAAAAAAAAAAAAAAAD//////////////AAAAAAAAAAAAAAAAAAAAH///' +
  '///////////gAAAAAAAAAAAAAAAAAAAD//////////////4AAAAAAAAAAAAAAAAAAAH/////////' +
  '/////8AAAAAAAAAAAAAAAAAAAP//////////////+AAAAAAAAAAAAAAAAAAA////////////////' +
  'AAAAAAAAAAAAAAAAAAB////////////////gAAAAAAAAAAAAAAAAAH////////////////4AAAAA' +
  'AAAAAAAAAAAAf////////////////8AAAAAAAAAAAAAAAAD/////////////////+AAAAAAAAAAA' +
  'AAAAA///////////////////AAAAAAAAAAAAAAB////////////////////gAAAAAAAAAAD/////' +
  '//////////////////wAAAAAAAAAAH///////////////////////8AAAAAAAAAAf///////////' +
  '////////////+AAAAAAAAAB/////////////////////////AAAAAAAAAB//////////////////' +
  '///////AAAAAAAAAD/////////////////////////gAAAAAAAAD////////////////////////' +
  '/4AAAAAAAAH/////////////////////////8AAAAAAAAf/////////////////////////8AAAA' +
  'AAAH//////////////////////////+AAAAAAAH///////////////////////////AAAAAAAD//' +
  '/////////////////////////gAAAAAAA///////////////////////////wAAAAAAAf///////' +
  '///////////////////wAAAAAAAH//////////////////////////4AAAAAAAD/////////////' +
  '/////////////8AAAAAAAA//////////////////////////+AAAAAAAAP//////////////////' +
  '///////+AAAAAAAAD//////////////////////////AAAAAAAAA////////////////////////' +
  '//AAAAAAAAAP/////////////////////////gAAAAAAAAD/////////////////////////gAAA' +
  'AAAAAAf////////////////////////wAAAAAAAAAD////////////////////////wAAAAAAAAA' +
  'A////////////////////////wAAAAAAAAAAD///////////////////////wAAAAAAAAAAAf///' +
  '///////////////////4AAAAAAAAAAAB//////////////////////4AAAAAAAAAAAAD////////' +
  '/////////////4AAAAAAAAAAAAAP////////////////////4AAAAAAAAAAAAAA/////////////' +
  '///////wAAAAAAAAAAAAAAH///////////////////4AAAAAAAAAAAAAAAf/////////////////' +
  '/wAAAAAAAAAAAAAAAB//////////////////wAAAAAAAAAAAAAAAAP/////////////////gAAAA' +
  'AAAAAAAAAAAAA/////////////////gAAAAAAAAAAAAAAAAAH////////////////wAAAAAAAAAA' +
  'AAAAAAAA////////////////gAAAAAAAAAAAAAAAAAAD///////////////AAAAAAAAAAAAAAAAA' +
  'AAAP/////////////+AAAAAAAAAAAAAAAAAAAAA/////////////4AAAAAAAAAAAAAAAAAAAAAB/' +
  '///////////4AAAAAAAAAAAAAAAAAAAAAAH///////////gAAAAAAAAAAAAAAAAAAAAAAAH/////' +
  '////8AAAAAAAAAAAAAAAAAAAAAAAAAD////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////4AA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAA==';

let unpacked: Uint8Array | null = null;

/** Lazily expand the packed rows to one byte per pixel. */
export function markBits(): Uint8Array {
  if (unpacked) return unpacked;
  const bin = atob(PACKED);
  const out = new Uint8Array(MARK_W * MARK_H);
  for (let i = 0; i < out.length; i++) {
    out[i] = (bin.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1;
  }
  unpacked = out;
  return out;
}
